// File generated by the FlutterFire CLI — this is a PLACEHOLDER.
//
// Run the real generator once you've created a Firebase project:
//   dart pub global activate flutterfire_cli
//   flutterfire configure
//
// That command overwrites this file with your project's real API
// keys/app IDs for Android, iOS, and Web and wires them into
// android/app/google-services.json and ios/Runner/GoogleService-Info.plist
// automatically. Do NOT ship the placeholder values below.

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const web = FirebaseOptions(
    apiKey: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    appId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    messagingSenderId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    projectId: 'safeher-app',
    storageBucket: 'safeher-app.appspot.com',
  );

  static const android = FirebaseOptions(
    apiKey: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    appId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    messagingSenderId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    projectId: 'safeher-app',
    storageBucket: 'safeher-app.appspot.com',
  );

  static const ios = FirebaseOptions(
    apiKey: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    appId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    messagingSenderId: 'REPLACE_WITH_FLUTTERFIRE_CONFIGURE',
    projectId: 'safeher-app',
    storageBucket: 'safeher-app.appspot.com',
    iosBundleId: 'com.safeher.app',
  );
}
